services:
  php:
    container_name: importer-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./app:/app
    working_dir: /app
    networks:
      - importer-network
    environment:
      PHP_IDE_CONFIG: 'serverName=importer-php'
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  importer-network: