services:
  php:
    container_name: importer-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./app:/app
    working_dir: /app
    networks:
      - importer-network
    environment:
      PHP_IDE_CONFIG: 'serverName=importer-php'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    container_name: importer-mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: importer
      MYSQL_PASSWORD: importer
      MYSQL_DATABASE: importer
    ports:
      - '3306:3306'
    networks:
      - importer-network
    volumes:
      - importer-database:/var/lib/mysql
    command: mysqld --general-log=1 --general-log-file=/var/lib/mysql/general-log.log

networks:
  importer-network:

volumes:
  importer-database: